# Generated by Django 2.2.2 on 2019-07-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='views',
        ),
        migrations.AddField(
            model_name='feature',
            name='phase_of_development',
            field=models.CharField(choices=[('Done', 'Done'), ('Doing', 'Doing'), ('ToDo', 'ToDo')], default='ToDo', max_length=6),
        ),
    ]
