# Generated by Django 2.2.3 on 2019-07-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_auto_20190717_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='vote_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=4),
        ),
    ]
