# Generated by Django 2.2.2 on 2019-06-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='fix_status',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Fixing', 'Fixing'), ('To Do', 'To Do')], default='To Do', max_length=10),
        ),
    ]
