# Generated by Django 2.2.2 on 2019-07-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0003_auto_20190630_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='fix_status',
            field=models.CharField(choices=[('DONE', 'Done'), ('DOING', 'Doing'), ('To Do', 'To Do')], default='To Do', max_length=10),
        ),
    ]
